@startuml
participant user
participant admin
participant app
database DB
user -> admin : registrarse
admin -> app : resgistrar
app --> admin : admision de registro
app -> DB : introduccion de datos para registro
user -> app : inicio de sesion
app -> DB : comprobacion de credenciales
alt caso de exito
DB --> app : credenciales correctas
app --> user : permiso para acceder
user -> app : introduccion de datos de piso
app -> DB : guardado de datos
alt caso de exito
DB --> app : datos guardados
app --> user : aviso de datos guardados
else
DB --> app : datos no guardados
app --> user : aviso de datos no guardados
end
user -> app : guardado de gastos e ingresos
app -> DB : introduccion de datos
alt caso de exito
DB --> app : guardado correcto
app --> user : aviso de guardado correcto
else caso de fallo
DB --> app : guardado erroneo
app --> user : aviso de no guardado
end
user -> app : visualizar los pisos y los datos de esos
app -> DB : registro de pisos y datos 
DB --> app : pisos registrados y sus datos
app --> user : visualizacion de pisos y datos
else algun problema o fallo
DB --> app : credenciales erroneas
app --> user : aviso de credenciales erroneas
end
@enduml
